---
- name: Django | Packages | Install required system packages.
  apt: >
    pkg=${item}
    state=installed
    update-cache=yes
  with_items:
    - build-essential
    - git
    - python-dev
    - python-setuptools
    - python-psycopg2
    - python-virtualenv
    - python-pip
    - postfix
    - libpq-dev
  tags:
    - base
    - packages
    - provision

