---
- name: Django | Settings | Create Django Database Settings Module
  template: >
    src=db.py.j2
    dest=${django.root}/${project.name}/settings/modules/db.py
  tags:
    - database
    - application
    - django
    - configuration
    - update

- name: Django | Settings | Create Django Cache Settings Module
  template: >
    src=cache.py.j2
    dest=${django.root}/${project.name}/settings/modules/cache.py
  tags:
    - cache
    - application
    - django
    - configuration
    - update

- name: Django | Settings | Create Django Celery Settings Module
  template: >
    src=celery.py.j2
    dest=${django.root}/${project.name}/settings/modules/celery.py
  tags:
    - cache
    - application
    - django
    - configuration
    - update



